steps:
#
# This step takes care of fetching cluster credentials (kubeconfig)
# DO NOT REMOVE THIS STEP
#
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'get'
  - 'pods'
  - '--all-namespaces'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'  

#
# Scan the target cluster.
# kubeconfig fetched by previous step
#
- name: 'alcide/advisor:stable'
  args:
  - --eula-sign
  - validate
  - cluster
  - --cluster-context
  - gke_${PROJECT_ID}_${_GKE_CLUSTER_ZONE}_${_GKE_CLUSTER}
  - '--namespace-include=*'
  - '--namespace-exclude=-'
  - '--outfile'
  - 'scan.html'
  #- '--policy-profile gold.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_CLUSTER_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'  

# artifacts:
#   objects:
#     location: 'gs://[STORAGE_LOCATION]/'
#     paths: ['scan.html']